/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package net.imthinker.ti.propchangehandler;

import android.app.Activity;
import android.content.SharedPreferences;
import android.content.SharedPreferences.OnSharedPreferenceChangeListener;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.titanium.TiApplication;

@Kroll.module(name = "Tipropchangehandler", id = "net.imthinker.ti.propchangehandler")
public class TipropchangehandlerModule extends KrollModule implements OnSharedPreferenceChangeListener {

    public TipropchangehandlerModule() {
        super();
    }

    @Kroll.onAppCreate
    public static void onAppCreate(TiApplication app) {
        //
    }

    @Override
    public void onResume(Activity activity) {
        super.onResume(activity);

        SharedPreferences sharedPreferences = activity.getSharedPreferences(
                TiApplication.APPLICATION_PREFERENCES_NAME,
                0
        );
        sharedPreferences.registerOnSharedPreferenceChangeListener(this);
    }

    @Override
    public void onSharedPreferenceChanged(SharedPreferences sharedPreferences,
                                          String key) {
        KrollDict krollDict = new KrollDict();
        krollDict.put("changekey", key);
        fireEvent("propchange", krollDict);
    }

}